Update requirements.txt (#917)
pandas>=0.23.4 is required to not encounter the following error when passing a holidays argument, since earlier in earlier version pandas the concat does not have a sort argument.

File "/usr/local/lib/python3.6/dist-packages/fbprophet/forecaster.py", line 454, in construct_holiday_dataframe
all_holidays = pd.concat((all_holidays, holidays_to_add), sort=False)
TypeError: concat() got an unexpected keyword argument 'sort'